from .add_product import resolve_add_product
from .add_product_to_cart import resolve_add_product_to_cart
from .assign_admin import resolve_assign_admin
from .create_user import resolve_create_user
from .delete_product import resolve_delete_product
from .delete_user import resolve_delete_user
from .get_cart import resolve_get_cart
from .get_product import resolve_get_product
from .get_products import resolve_get_products
from .get_user import resolve_get_user
from .get_users import resolve_get_users
from .login_user import resolve_login_user
from .update_product import resolve_update_product
from .remove_one_product_from_cart import resolve_remove_one_product_from_cart
