"""add prod characteristics

Revision ID: 165811bed174
Revises: 7c3b6c90af74
Create Date: 2022-10-07 17:19:20.145283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165811bed174'
down_revision = '7c3b6c90af74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_characteristics',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'characteristic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_characteristics')
    op.drop_table('characteristics')
    # ### end Alembic commands ###
