"""delete url from ProductImage

Revision ID: 25320a4ba9e4
Revises: 5401ebdc0bd2
Create Date: 2022-08-31 20:26:47.964893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25320a4ba9e4'
down_revision = '5401ebdc0bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
