"""add product_images table

Revision ID: 5401ebdc0bd2
Revises: 96e60dcd6b0c
Create Date: 2022-08-27 21:59:18.729434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5401ebdc0bd2'
down_revision = '96e60dcd6b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('product_images')
    # ### end Alembic commands ###
