"""delete Cart table, CartLine cart_id changed to user_id

Revision ID: 96e60dcd6b0c
Revises: a9cafbc42b3a
Create Date: 2022-08-24 23:18:37.608556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e60dcd6b0c'
down_revision = 'a9cafbc42b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    op.add_column('cartlines', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('cartlines_cart_id_fkey', 'cartlines', type_='foreignkey')
    op.create_foreign_key(None, 'cartlines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cartlines', 'cart_id')
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('cartlines', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cartlines', type_='foreignkey')
    op.create_foreign_key('cartlines_cart_id_fkey', 'cartlines', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cartlines', 'user_id')
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='carts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='carts_pkey'),
    sa.UniqueConstraint('user_id', name='carts_user_id_key')
    )
    # ### end Alembic commands ###
