"""add image_name and is_preview to ProductImage

Revision ID: 9d58d229fc86
Revises: 25320a4ba9e4
Create Date: 2022-09-01 19:46:01.779815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d58d229fc86'
down_revision = '25320a4ba9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('image_name', sa.String(), nullable=False))
    op.add_column('product_images', sa.Column('is_preview', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'is_preview')
    op.drop_column('product_images', 'image_name')
    # ### end Alembic commands ###
