"""expansion of products

Revision ID: 9eb8d169a5c2
Revises: ef47c352b452
Create Date: 2022-08-19 15:39:27.589312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb8d169a5c2'
down_revision = 'ef47c352b452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'amount')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
