"""add products.reserved

Revision ID: b0884f873094
Revises: e16167402ebc
Create Date: 2022-10-05 15:48:48.865525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0884f873094'
down_revision = 'e16167402ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reserved', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reserved')
    # ### end Alembic commands ###
