"""orders.date to creation/completion_date

Revision ID: ca31833ef492
Revises: b0baae96583e
Create Date: 2022-10-05 19:44:08.412351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca31833ef492'
down_revision = 'b0baae96583e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('creation_date', sa.Date(), nullable=False))
    op.add_column('orders', sa.Column('completion_date', sa.Date(), nullable=True))
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'completion_date')
    op.drop_column('orders', 'creation_date')
    # ### end Alembic commands ###
